# Site
name: 'The Chambana Report'
description: 'The Chambana Report is a newspaper that covers stories from Urbana to Champaign.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: "https://www.chambanareport.org"
disqus: ''
email: 'jfhogg2@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jon:
      name:           Jon 
      site:           https://github.com/KingKoolKat
      avatar:         /assets/images/avatar1.jpeg
      bio:            "Jon is the editor in chief and technical director of the Chambana Report. He once embarassed himself in a Guitar Center because he grossly underestimated the difficulty of playing drums. He has a seasonal interest in snails and dreams to name the shiftiest one \"Snail Gilgeous Alexander\"."
      email:          jfhogg2@illinois.edu
             

    david:
      name:           David 
      site:           https://www.goodreads.com/user/show/176166177-david-hipp 
      avatar:         /assets/images/david pfp.jpeg
      bio:            "David is the creative director and an investigative journalist for the newspaper. He enjoys relaxing in nature, listening to music, and hanging out with friends. He wouldn't describe himself as eclectic but hopes that other people might describe him as such."
      email:          dhipp2@illinois.edu
    
    ryan:
      name:           Ryan
      site:           https://google.com
      avatar:         /assets/images/square ryan.jpeg
      bio:            "Ryan is the chief final officer, a columnist, and a doctor of journalism who currently attends several different universities under several different seasonal-themed last names. His hobbies include listening to spotify, clash royale, and writing his biweekly advice column. His list of role models includes Puss in Boots and Clairo, among others."
      email:          ryanm21@illinois.edu      
    drafty:
      name:           Drafty
      site:           https://batconservationalliance.org
      avatar:         /assets/images/Chambana Report Mascot Logo-01.jpg
      bio:            "Drafty is a bat(?) but more importantly is an intern at the Chambana Report. They handle various odds and ends. Drafty dreams of writing for the Chambana Report but isn't able to make it past a first draft. Drafty loves ultimate frisbee."
      email:          jfhogg2@illinois.edu    
    tony:
      name:           Tony
      site:           https://www.strongtowns.org
      avatar:         /assets/images/tonynew.png
      bio:            "Tony is a writer, a student of the streets and bicycle philosopher. A true modern renaissance man, he silently sits in coffee shops for hours at a time while purchasing nothing and holds a municipal internship in a windowless closet."
      email:          anthonymcrispin@gmail.com
    jaxon:
      name:           Jaxon
      site:           https://www.instagram.com/ja.xro?igsh=MWJicjM3NnQ3Z2x4Nw==
      avatar:         /assets/images/jaxoncrop.jpeg
      bio:            "Jaxon is just an intern, currently trying to dabble in a few projects, get a sense of things here and there and maybe try a few tricks out. I would recommend staying tuned for future character development, but currently he likes riding a bike or going on the computer to look at maps."
      email:          jaxonr2@illinois.edu
    eamon:
      name:           E.C. Gerber
      site:           https://www.depop.com/buffalokids/
      avatar:         /assets/images/eamon.jpeg
      bio:            "E.C. Gerber takes very cold showers. He walks through Urbana and looks down the drainage holes for Pennywise-like characters. To keep the children safe. He organizes his National Geographic papers by month and date, as his grandparents did before him. Novice reporter."
      email:          lfcampz1@gmail.com
    thomas:
      name:           Thomas Dickey
      site:           https://www.lpzoo.org
      avatar:         /assets/images/thomas.jpeg
      bio:            "Thomas Dickey is an environmentalist, wildlife educator, and television personality. He graduated from the Medal School of Journalism in 2023. He aspires to one day live in or near a zoo."
      email:          jfhogg2@illinois.edu
    owen:
      name:           Owen Valentine
      site:           https://open.spotify.com/artist/2OR6qp88OBhFfldNiovnoz?si=NszAeUgOT4W4pfvxC-Nv8A
      avatar:         /assets/images/owen.jpeg
      bio:            "Owen Valentine is a genre-bending musical genius who occasionally lends his pen to the Chambana Report. He was once belittled by the employees at a Taco Bell drive thru for ordering cheese quesadillas. He has a very shallow Overwatch hero pool."
      email:          owenecurran@gmail.com


    
             
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jon
      avatar: /assets/images/avatar1.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
